theme: jekyll-theme-hacker
title:            fatbardhkadriu
tagline:          'Computer Engineering'
description:      'Electrical and Computer Engineering'
url:              https://fatbardhkadriu.github.io
lang:             sq
